eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8000
spring:
    application:
        name: GATEWAY-SERVICE
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"

